### ISSUE TITLE
unable to open message file

### ISSUE THREAD

**Issue by mengfeimu** [djlampert/PyHSPF#4]
It seems WDMUtil runs into some problems. When I run examples/test/test01.py, the error shows:
```
unable to open message file
```
I copied hspfmsg.wdm to another folder, but it didn't work. Do you have any idea what's the reason behind this?
By the way, I installed the pyhspf 0.2.4 from [PyPI](https://pypi.org/project/pyhspf/#files) few days ago.
Thanks!

**Comment by mengfeimu** [comment]
I temporally solved this problem by set messagepath to the hspfmsg.wdm in BASINS software folder:
```python
messagepath = 'C:/BASINS41/bin/Plugins/BASINS/hspfmsg.wdm'
wdm = WDMUtil(verbose = True, messagepath = messagepath)
```
I tried to copy BASINS/hspfmsg.wdm into pyhspf/core/ and replace the original hspfmsg.wdm, but it didn't work.

This is a temporal solution for the problem. Hope anyone can find the reason behind the problem.

**Comment by mishranurag** [comment]
I use SARA Time Series Utility for all WMD related tasks. WDMUtil is not supported anymore.

**Comment by djlampert** [comment]
The problem is not the message file in the core directory, but is usually related to the length of the absolute path exceeding 64 characters, which is hard-coded into the program. We have added some documentation to help point this out. You can work around the limit by providing the path the hspfmsf.wdm. I would use the version that exists with this build of hspf.
